# Generated by Django 4.0.2 on 2022-05-09 14:35

import api.domain.images_models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='TrackEventBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click')], max_length=5, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'TrackEventBody',
                'verbose_name_plural': 'TrackEventBodies',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Image ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('weight', models.FloatField(default=0.0, verbose_name='Weight')),
                ('grid_position', models.PositiveSmallIntegerField(default=0, verbose_name='Grid Position')),
                ('url', models.URLField(verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('events', models.OneToOneField(default=api.domain.images_models.default_events, on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
            options={
                'verbose_name': 'ImageInfo',
                'verbose_name_plural': 'ImagesInfo',
                'ordering': ['-weight', '-created_at'],
            },
        ),
    ]
